### ISSUE TITLE
Old Junk keeps reappearing

### ISSUE THREAD

**Issue by Calorion** [WebVeteran/SpamCop-Deputy#4] opened 2018-03-25 16:27 UTC
When I run SpamCop Deputy, at the end of it my junk mail folder is empty. The next day, all of the junk it had previously deleted is back, though unread.

**Comment by WebVeteran** [comment] 2018-03-25 17:40
That's a known issue. But not with Deputy per se. It's something to do with deleting messages with Applescript. For me, the issue disappeared on it's own, and only comes back on very rare occurrences. I think the issue is because of another process also IMAPing into the same email account. Like an iPhone. Such that the Mac deletes the message in a way that the phone does not get the imap command to delete the message too. That somehow resurrects the message via the phone pushing it back to the IMAP server, then back to the Mac. It's conjecture at this point though.

Please let me know your scenario. Maybe I can narrow it down.

**Comment by Calorion** [comment] 2018-03-25 17:42
Hm. Yeah. I have multiple devices IMAPing (Mac, iPhone, iPad) into the same account, including an iMac which generally has its mail client open all the time to run rules. So something like this is likely what's happening.

**Comment by WebVeteran** [comment] 2019-09-16 03:32
I haven't seen this happen in a very long time. I think Apple fixed something. Closing for now.

**Closed by WebVeteran** 2019-09-16 03:32 UTC

**Comment by Calorion** [comment] 2020-08-27 22:33
This is still happening in El Capitan. I’ve found a fix here: https://discussions.apple.com/thread/6164090

I’ve implemented it in my installation, and it seems to be working.

**Comment by Calorion** [comment] 2020-08-27 22:33
This is still happening in El Capitan. I’ve found a fix here: https://discussions.apple.com/thread/6164090

I’ve implemented it in my installation, and it seems to be working.

**Comment by Calorion** [comment] 2020-08-27 22:33
This is still happening in El Capitan. I’ve found a fix here: https://discussions.apple.com/thread/6164090

I’ve implemented it in my installation, and it seems to be working.

**Comment by Calorion** [comment] 2020-08-27 22:33
This is still happening in El Capitan. I’ve found a fix here: https://discussions.apple.com/thread/6164090

I’ve implemented it in my installation, and it seems to be working.

**Comment by Calorion** [comment] 2020-09-12 21:12
For future reference, here’s the details of the fix.

Near the end of 👮🏻SpamCopNotify.scpt, replace
`delete thisMessage`

with
`set theAccount to account of mailbox of thisMessage`
`set mailbox of thisMessage to mailbox "Trash" of theAccount`

**Comment by Calorion** [comment] 2020-10-20 22:38
Update: This script fails with live.com accounts, because they lack a “Trash” mailbox. Instead, use this:

`set theAccount to account of mailbox of thisMessage`
`set mailbox of thisMessage to mailbox “Trash”`

and the spam will be directed to the local Trash mailbox.
